#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Test-Most
Version  : 0.35
Release  : 11
URL      : https://cpan.metacpan.org/authors/id/O/OV/OVID/Test-Most-0.35.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/O/OV/OVID/Test-Most-0.35.tar.gz
Summary  : unknown
Group    : Development/Tools
License  : GPL-1.0
BuildRequires : buildreq-cpan
BuildRequires : perl(Algorithm::Diff)
BuildRequires : perl(Class::Data::Inheritable)
BuildRequires : perl(Devel::StackTrace)
BuildRequires : perl(Exception::Class)
BuildRequires : perl(Sub::Uplevel)
BuildRequires : perl(Test::Deep)
BuildRequires : perl(Test::Differences)
BuildRequires : perl(Test::Exception)
BuildRequires : perl(Test::Warn)
BuildRequires : perl(Text::Diff)

%description
INSTALLATION
To install this module, run the following commands:
perl Build.PL
./Build
./Build test
./Build install

%package dev
Summary: dev components for the perl-Test-Most package.
Group: Development
Provides: perl-Test-Most-devel = %{version}-%{release}

%description dev
dev components for the perl-Test-Most package.


%prep
%setup -q -n Test-Most-0.35

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.28.2/Test/Most.pm
/usr/lib/perl5/vendor_perl/5.28.2/Test/Most/Exception.pm

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::Most.3
/usr/share/man/man3/Test::Most::Exception.3
